export interface FranchiseItem {
  id: string;
  name: string;
  slug: string;
  logo: string;
  category: string;
  isFeatured: boolean;
  description: string;
  headquarters: string;
  startupCost: string;
  totalInvestment: string;
  franchisingSince: string;
  phone: string;
  email: string;
  website: string;
}

export const ALL_FRANCHISES: FranchiseItem[] = [
  { id: "1", name: "Eeeng RQH", slug: "eeeng-rqh", logo: "/complogo/1.png", category: "Еда и рестораны", isFeatured: true, description: "Eeeng RQH — уникальная концепция ресторана с авторской кухней и оригинальной подачей блюд.", headquarters: "Ташкент, Узбекистан", startupCost: "$20K - $40K", totalInvestment: "$80K - $150K", franchisingSince: "2020", phone: "+998 90 123 45 67", email: "info@eeeng-rqh.uz", website: "#" },
  { id: "2", name: "Apex Pizza", slug: "apex-pizza", logo: "/complogo/2.png", category: "Еда и рестораны", isFeatured: true, description: "Apex Pizza — сеть пиццерий с уникальными рецептами и быстрой доставкой. Свежие ингредиенты, современное оборудование.", headquarters: "Ташкент, Узбекистан", startupCost: "$15K - $30K", totalInvestment: "$50K - $100K", franchisingSince: "2019", phone: "+998 90 234 56 78", email: "franchise@apexpizza.uz", website: "#" },
  { id: "3", name: "Любятово", slug: "lubyatovo", logo: "/complogo/3.png", category: "Еда и рестораны", isFeatured: false, description: "Любятово — российский бренд кондитерских изделий и снеков с многолетней историей и высоким качеством продукции.", headquarters: "Россия", startupCost: "$30K - $60K", totalInvestment: "$100K - $200K", franchisingSince: "1999", phone: "+7 495 123 45 67", email: "franchise@lubyatovo.ru", website: "#" },
  { id: "4", name: "GMLB", slug: "gmlb", logo: "/complogo/4.png", category: "IT и технологии", isFeatured: true, description: "GMLB Automation — автоматизация бизнес-процессов для малого и среднего бизнеса. Боты, воронки, аналитика, парсеры.", headquarters: "Ташкент, Узбекистан", startupCost: "$5K - $15K", totalInvestment: "$10K - $30K", franchisingSince: "2024", phone: "+998 90 345 67 89", email: "info@gmlb.ru", website: "https://gmlb.ru" },
  { id: "5", name: "Shavi", slug: "shavi", logo: "/complogo/5.png", category: "Еда и рестораны", isFeatured: false, description: "Shavi — сеть кафе-ресторанов с восточной кухней и современной подачей.", headquarters: "Ташкент, Узбекистан", startupCost: "$25K - $50K", totalInvestment: "$80K - $160K", franchisingSince: "2021", phone: "+998 90 456 78 90", email: "info@shavi.uz", website: "#" },
  { id: "6", name: "Vasilchuki Chaihona №1", slug: "vasilchuki-chaihona", logo: "/complogo/6.png", category: "Еда и рестораны", isFeatured: true, description: "Vasilchuki Chaihona №1 — легендарная сеть ресторанов восточной кухни от братьев Васильчук. Аутентичная чайхона с современным подходом.", headquarters: "Россия / Ташкент", startupCost: "$80K - $150K", totalInvestment: "$250K - $500K", franchisingSince: "2012", phone: "+998 90 567 89 01", email: "franchise@chaihona1.uz", website: "#" },
  { id: "7", name: "Cyber X Community", slug: "cyber-x-community", logo: "/complogo/7.png", category: "Развлечения", isFeatured: true, description: "Cyber X Community — киберспортивная площадка и комьюнити-центр для геймеров.", headquarters: "Ташкент, Узбекистан", startupCost: "$30K - $60K", totalInvestment: "$100K - $250K", franchisingSince: "2022", phone: "+998 90 678 90 12", email: "info@cyberx.uz", website: "#" },
  { id: "8", name: "Women Kids", slug: "women-kids", logo: "/complogo/8.png", category: "Детские услуги", isFeatured: false, description: "Women Kids — сеть развивающих центров для детей и молодых мам.", headquarters: "Ташкент, Узбекистан", startupCost: "$15K - $35K", totalInvestment: "$40K - $90K", franchisingSince: "2020", phone: "+998 90 789 01 23", email: "info@womenkids.uz", website: "#" },
  { id: "9", name: "Eat Pizza", slug: "eat-pizza", logo: "/complogo/9.png", category: "Еда и рестораны", isFeatured: true, description: "Eat Pizza — корейская сеть пиццерий с уникальными вкусами и стильным дизайном заведений.", headquarters: "Корея / Ташкент", startupCost: "$20K - $45K", totalInvestment: "$70K - $140K", franchisingSince: "2018", phone: "+998 90 890 12 34", email: "franchise@eatpizza.uz", website: "#" },
  { id: "10", name: "Chortoq", slug: "chortoq", logo: "/complogo/10.png", category: "Еда и рестораны", isFeatured: false, description: "Chortoq — ресторан национальной узбекской кухни с горной тематикой и панорамными видами.", headquarters: "Ташкент, Узбекистан", startupCost: "$40K - $80K", totalInvestment: "$150K - $300K", franchisingSince: "2017", phone: "+998 90 901 23 45", email: "info@chortoq.uz", website: "#" },
  { id: "11", name: "Руки Вверх Бар", slug: "ruki-vverh-bar", logo: "/complogo/11.png", category: "Еда и рестораны", isFeatured: true, description: "Руки Вверх Бар — сеть развлекательных баров с живой музыкой, караоке и атмосферой 90-х.", headquarters: "Россия / Ташкент", startupCost: "$50K - $100K", totalInvestment: "$200K - $400K", franchisingSince: "2019", phone: "+998 90 012 34 56", email: "franchise@rukivverh.bar", website: "#" },
  { id: "12", name: "KIMS First Line", slug: "kims-first-line", logo: "/complogo/12.png", category: "Красота и здоровье", isFeatured: false, description: "KIMS First Line — премиальный бренд косметики и средств по уходу за кожей.", headquarters: "Корея / Ташкент", startupCost: "$10K - $25K", totalInvestment: "$30K - $70K", franchisingSince: "2021", phone: "+998 90 111 22 33", email: "info@kimsfirstline.uz", website: "#" },
  { id: "13", name: "Ключ под Ключ", slug: "kluch-pod-kluch", logo: "/complogo/13.png", category: "Бизнес-услуги", isFeatured: false, description: "Ключ под Ключ — сеть ключных мастерских с полным спектром услуг по изготовлению и ремонту ключей.", headquarters: "Россия / Ташкент", startupCost: "$5K - $15K", totalInvestment: "$15K - $35K", franchisingSince: "2020", phone: "+998 90 222 33 44", email: "info@kluchpodkluch.uz", website: "#" },
  { id: "14", name: "Cafe BomBom", slug: "cafe-bombom", logo: "/complogo/14.png", category: "Напитки", isFeatured: false, description: "Cafe BomBom — корейская сеть кофеен с авторскими напитками и десертами.", headquarters: "Корея / Ташкент", startupCost: "$15K - $30K", totalInvestment: "$40K - $80K", franchisingSince: "2022", phone: "+998 90 333 44 55", email: "info@cafebombom.uz", website: "#" },
  { id: "15", name: "Steak It Easy", slug: "steak-it-easy", logo: "/complogo/15.png", category: "Еда и рестораны", isFeatured: true, description: "Steak It Easy — Josper Wine Bar. Премиальные стейки, приготовленные на хоспере, в сочетании с лучшими винами.", headquarters: "Ташкент, Узбекистан", startupCost: "$60K - $120K", totalInvestment: "$200K - $450K", franchisingSince: "2019", phone: "+998 90 444 55 66", email: "franchise@steakiteasy.uz", website: "#" },
  { id: "16", name: "Ruski Restaurant", slug: "ruski-restaurant", logo: "/complogo/16.png", category: "Еда и рестораны", isFeatured: false, description: "Ruski Restaurant — ресторан русской кухни премиум-класса с традиционными блюдами.", headquarters: "Россия / Ташкент", startupCost: "$50K - $100K", totalInvestment: "$150K - $350K", franchisingSince: "2018", phone: "+998 90 555 66 77", email: "info@ruski.uz", website: "#" },
  { id: "17", name: "Bellissimo Pizza", slug: "bellissimo-pizza", logo: "/complogo/17.png", category: "Еда и рестораны", isFeatured: true, description: "Bellissimo Pizza — одна из крупнейших сетей пиццерий в Узбекистане. Итальянская пицца с доставкой.", headquarters: "Ташкент, Узбекистан", startupCost: "$30K - $60K", totalInvestment: "$100K - $200K", franchisingSince: "2015", phone: "+998 90 666 77 88", email: "franchise@bellissimo.uz", website: "#" },
  { id: "18", name: "Shox International Hospital", slug: "shox-hospital", logo: "/complogo/18.png", category: "Красота и здоровье", isFeatured: false, description: "Shox International Hospital — сеть многопрофильных медицинских клиник с международными стандартами обслуживания.", headquarters: "Ташкент, Узбекистан", startupCost: "$200K - $500K", totalInvestment: "$500K - $1.5M", franchisingSince: "2010", phone: "+998 90 777 88 99", email: "info@shoxhospital.uz", website: "#" },
  { id: "19", name: "Caffelito", slug: "caffelito", logo: "/complogo/19.png", category: "Напитки", isFeatured: false, description: "Caffelito — сеть кофеен с собственной обжаркой кофейных зёрен и уютной атмосферой.", headquarters: "Ташкент, Узбекистан", startupCost: "$10K - $25K", totalInvestment: "$30K - $60K", franchisingSince: "2021", phone: "+998 90 888 99 00", email: "info@caffelito.uz", website: "#" },
  { id: "20", name: "Cannar", slug: "cannar", logo: "/complogo/20.png", category: "Бизнес-услуги", isFeatured: false, description: "Cannar — консалтинговая компания и бизнес-платформа для предпринимателей.", headquarters: "Ташкент, Узбекистан", startupCost: "$10K - $20K", totalInvestment: "$20K - $50K", franchisingSince: "2022", phone: "+998 90 999 00 11", email: "info@cannar.uz", website: "#" },
  { id: "21", name: "Gipopo Natural", slug: "gipopo-natural", logo: "/complogo/21.png", category: "Детские услуги", isFeatured: false, description: "Gipopo Natural — бренд натуральных детских товаров и продуктов питания для малышей.", headquarters: "Ташкент, Узбекистан", startupCost: "$10K - $20K", totalInvestment: "$25K - $55K", franchisingSince: "2023", phone: "+998 90 100 20 30", email: "info@gipopo.uz", website: "#" },
  { id: "22", name: "Шеф Burger", slug: "shef-burger", logo: "/complogo/22.png", category: "Еда и рестораны", isFeatured: true, description: "Шеф Burger — сеть бургерных ресторанов с авторскими рецептами шеф-поваров.", headquarters: "Россия / Ташкент", startupCost: "$25K - $50K", totalInvestment: "$80K - $160K", franchisingSince: "2018", phone: "+998 90 200 30 40", email: "franchise@shefburger.uz", website: "#" },
  { id: "23", name: "Space Coworking", slug: "space-coworking", logo: "/complogo/23.png", category: "Бизнес-услуги", isFeatured: false, description: "Space Coworking — современные коворкинг-пространства для фрилансеров, стартапов и команд.", headquarters: "Ташкент, Узбекистан", startupCost: "$30K - $70K", totalInvestment: "$100K - $250K", franchisingSince: "2021", phone: "+998 90 300 40 50", email: "info@spacecoworking.uz", website: "#" },
  { id: "24", name: "Черноголовка", slug: "chernogolovka", logo: "/complogo/24.png", category: "Напитки", isFeatured: false, description: "Черноголовка — легендарный российский бренд безалкогольных напитков с вековой историей.", headquarters: "Россия / Ташкент", startupCost: "$40K - $80K", totalInvestment: "$120K - $250K", franchisingSince: "1942", phone: "+998 90 400 50 60", email: "franchise@chernogolovka.uz", website: "#" },
  { id: "25", name: "Трактир Холоп", slug: "traktir-holop", logo: "/complogo/25.png", category: "Еда и рестораны", isFeatured: false, description: "Трактир Холоп — сеть ресторанов русской кухни в традиционном стиле.", headquarters: "Россия / Ташкент", startupCost: "$40K - $80K", totalInvestment: "$130K - $280K", franchisingSince: "2017", phone: "+998 90 500 60 70", email: "info@traktirholop.uz", website: "#" },
  { id: "26", name: "Чебурашка", slug: "cheburashka", logo: "/complogo/26.png", category: "Еда и рестораны", isFeatured: false, description: "Чебурашка — семейный ресторан с детским меню, развлечениями и уютной атмосферой для всей семьи.", headquarters: "Россия / Ташкент", startupCost: "$35K - $70K", totalInvestment: "$100K - $220K", franchisingSince: "2019", phone: "+998 90 600 70 80", email: "info@cheburashka.uz", website: "#" },
  { id: "27", name: "ФинГрам", slug: "fingram", logo: "/complogo/27.png", category: "Финансовые услуги", isFeatured: false, description: "ФинГрам — образовательная платформа по финансовой грамотности для детей и взрослых.", headquarters: "Ташкент, Узбекистан", startupCost: "$5K - $15K", totalInvestment: "$15K - $40K", franchisingSince: "2023", phone: "+998 90 700 80 90", email: "info@fingram.uz", website: "#" },
  { id: "28", name: "ROBBO", slug: "robbo", logo: "/complogo/28.png", category: "Образование", isFeatured: false, description: "ROBBO — международная сеть школ робототехники и программирования для детей.", headquarters: "Финляндия / Ташкент", startupCost: "$15K - $30K", totalInvestment: "$30K - $70K", franchisingSince: "2016", phone: "+998 90 800 90 01", email: "franchise@robbo.uz", website: "#" },
  { id: "29", name: "Resto Market by Vasilchuki", slug: "resto-market", logo: "/complogo/29.png", category: "Еда и рестораны", isFeatured: false, description: "Resto Market by Vasilchuki — гастрономический рынок с несколькими концепциями еды под одной крышей.", headquarters: "Россия / Ташкент", startupCost: "$60K - $120K", totalInvestment: "$200K - $500K", franchisingSince: "2018", phone: "+998 90 900 01 12", email: "info@restomarket.uz", website: "#" },
  { id: "30", name: "ПЭК", slug: "pek", logo: "/complogo/30.png", category: "Логистика", isFeatured: false, description: "ПЭК — Первая Экспедиционная Компания. Крупнейший логистический оператор с сетью по всему СНГ.", headquarters: "Россия / Ташкент", startupCost: "$50K - $100K", totalInvestment: "$150K - $350K", franchisingSince: "2001", phone: "+998 90 010 12 23", email: "franchise@pecom.uz", website: "#" },
  { id: "31", name: "Мясной Steak House", slug: "myasnoy-steak-house", logo: "/complogo/31.png", category: "Еда и рестораны", isFeatured: false, description: "Мясной Steak House — стейк-хаус с девизом «Жарим по любви». Премиальное мясо на гриле.", headquarters: "Россия / Ташкент", startupCost: "$45K - $90K", totalInvestment: "$150K - $300K", franchisingSince: "2017", phone: "+998 90 020 23 34", email: "info@myasnoy.uz", website: "#" },
  { id: "32", name: "Кочевники", slug: "kochevniki", logo: "/complogo/32.png", category: "Еда и рестораны", isFeatured: false, description: "Кочевники — ресторан с кочевой кухней народов Центральной Азии. Аутентичные блюда и атмосфера.", headquarters: "Ташкент, Узбекистан", startupCost: "$35K - $70K", totalInvestment: "$100K - $220K", franchisingSince: "2020", phone: "+998 90 030 34 45", email: "info@kochevniki.uz", website: "#" },
  { id: "33", name: "St.Petersburg Business Center", slug: "st-petersburg-bc", logo: "/complogo/33.png", category: "Бизнес-услуги", isFeatured: false, description: "St.Petersburg Business Center — сеть бизнес-центров премиум-класса для аренды офисов и конференц-залов.", headquarters: "Россия / Ташкент", startupCost: "$100K - $300K", totalInvestment: "$300K - $800K", franchisingSince: "2015", phone: "+998 90 040 45 56", email: "info@spbbc.uz", website: "#" },
  { id: "34", name: "Choupette", slug: "choupette", logo: "/complogo/34.png", category: "Детские услуги", isFeatured: false, description: "Choupette — бренд детской одежды премиум-класса. Стильная и качественная одежда для детей от 0 до 12 лет.", headquarters: "Россия / Ташкент", startupCost: "$20K - $40K", totalInvestment: "$50K - $120K", franchisingSince: "2007", phone: "+998 90 050 56 67", email: "franchise@choupette.uz", website: "#" },
  { id: "35", name: "Ai-CHA Ice Cream & Tea", slug: "ai-cha", logo: "/complogo/35.png", category: "Напитки", isFeatured: false, description: "Ai-CHA — сеть чайных и мороженого с азиатскими вкусами и милым дизайном.", headquarters: "Азия / Ташкент", startupCost: "$10K - $25K", totalInvestment: "$25K - $60K", franchisingSince: "2022", phone: "+998 90 060 67 78", email: "info@aicha.uz", website: "#" },
  { id: "36", name: "Spaces Netwrk", slug: "spaces-netwrk", logo: "/complogo/36.png", category: "Бизнес-услуги", isFeatured: false, description: "Spaces Netwrk — коворкинги и офисные пространства нового поколения.", headquarters: "Ташкент, Узбекистан", startupCost: "$40K - $80K", totalInvestment: "$120K - $300K", franchisingSince: "2023", phone: "+998 90 070 78 89", email: "info@spacesnetwrk.uz", website: "#" },
  { id: "37", name: "Dito Italiano", slug: "dito-italiano", logo: "/complogo/37.png", category: "Еда и рестораны", isFeatured: false, description: "Dito Italiano — сеть аутентичных итальянских ресторанов с пастой ручной работы.", headquarters: "Италия / Ташкент", startupCost: "$35K - $70K", totalInvestment: "$100K - $250K", franchisingSince: "2021", phone: "+998 90 080 89 90", email: "info@ditoitaliano.uz", website: "#" },
  { id: "38", name: "Socials Cozy Cafe", slug: "socials-cozy-cafe", logo: "/complogo/38.png", category: "Напитки", isFeatured: false, description: "Socials Cozy Cafe — уютная сеть кафе для общения и работы с авторскими напитками.", headquarters: "Ташкент, Узбекистан", startupCost: "$12K - $25K", totalInvestment: "$30K - $65K", franchisingSince: "2023", phone: "+998 90 090 90 01", email: "info@socialscafe.uz", website: "#" },
  { id: "39", name: "Yapona Mama", slug: "yapona-mama", logo: "/complogo/39.png", category: "Еда и рестораны", isFeatured: false, description: "Yapona Mama — сеть ресторанов японской кухни с доставкой. Суши, роллы и рамен.", headquarters: "Россия / Ташкент", startupCost: "$25K - $50K", totalInvestment: "$70K - $150K", franchisingSince: "2018", phone: "+998 90 011 12 23", email: "franchise@yaponamama.uz", website: "#" },
  { id: "40", name: "Ediya Coffee", slug: "ediya-coffee", logo: "/complogo/40.png", category: "Напитки", isFeatured: false, description: "Ediya Coffee — крупнейшая сеть кофеен Южной Кореи. Доступный премиальный кофе.", headquarters: "Корея / Ташкент", startupCost: "$20K - $45K", totalInvestment: "$60K - $130K", franchisingSince: "2001", phone: "+998 90 022 23 34", email: "franchise@ediyacoffee.uz", website: "#" },
];

export function getFranchiseBySlug(slug: string): FranchiseItem | undefined {
  return ALL_FRANCHISES.find((f) => f.slug === slug);
}
